### ISSUE TITLE
Steering motor wattage calculation

### ISSUE THREAD

**Issue by Vaslouk** [vasilepi/Space-Rover#10]

**Comment by vasilepi** [comment]
To calculate this:
$$\tau_{steering}=I\cdot \alpha + \tau_{friction}$$
The inertia of the wheel is found through Onshape as:
![image](https://github.com/vasilepi/Space-Rover/assets/132815921/f9859bc8-ada9-410a-88a7-980e7aad8072)
the one in question is Lzz.\
The angular acceleration is considered as $1\ deg/s^2$. The $\tau_{friction}$ should be the same as the rolling resistance torque in #7 . Then the wattage of the motor is:
$$P=\tau_{steering} \cdot \omega $$
$$\omega=1\ deg/s^2 \cdot \frac{\pi}{180} \cdot \Delta t$$
Considering a total $\Delta t=8\ s$ for the wheel to steer overtime, we can calculate the total wattage for the motor.

**Comment by vasilepi** [comment]
> To calculate this: τsteering=I⋅α+τfriction The inertia of the wheel is found through Onshape as: ![image](https://github.com/vasilepi/Space-Rover/assets/132815921/f9859bc8-ada9-410a-88a7-980e7aad8072) the one in question is Lzz. The angular acceleration is considered as 1 deg/s2. The τfriction should be the same as the rolling resistance torque in #7 . Then the wattage of the motor is: P=τsteering⋅ω ω=1 deg/s2⋅π180⋅Δt Considering a total Δt=8 s for the wheel to steer overtime, we can calculate the total wattage for the motor.

The value of wattage comes out to be:
P>2W
