### ISSUE TITLE
Power design of robotic arm

### ISSUE THREAD

**Issue by vasilepi** [vasilepi/Space-Rover#14]
This is to calculate the dc motor wattage and quantity required to moved the robotic arm.
steps:

- [ ] mass of robotic arm evaluation
- [ ] come up with general design idea

**Comment by Theorestis** [comment]
![IMG_20231122_180745](https://github.com/vasilepi/Space-Rover/assets/149178240/e5337de9-ceab-40db-9055-6d4971328aaa)

**Comment by Theorestis** [comment]
Ro

> ![IMG_20231122_180745](https://user-images.githubusercontent.com/149178240/284968621-e5337de9-ceab-40db-9055-6d4971328aaa.jpg)

Robotic arm very simple free body diagram.

**Comment by Tasosgo** [comment]
![image](https://github.com/vasilepi/Space-Rover/assets/149701302/9efbb5b2-d3ac-4c14-8535-047d11dcd5e6)
'

**Comment by Tasosgo** [comment]
[Uploading torque calculation for servos.pdf…]()
