### ISSUE TITLE
panels 3d cad design

### ISSUE THREAD

**Issue by vasilepi** [vasilepi/Space-Rover#15]
this is for designing the panel deployment mechanism cad

**Comment by Theorestis** [comment]
https://github.com/vasilepi/Space-Rover/assets/149178240/9a79ad33-56fe-4093-80e1-539d16479105

**Comment by Theorestis** [comment]
> received_2346241089098141.mp4

3d panel deployment assembled mechanism.
This is how panel fold and unfold.
