### ISSUE TITLE
Robotic Arm

### ISSUE THREAD

**Issue by vasilepi** [vasilepi/Space-Rover#2]

**Comment by Tilihub** [comment]
![IMG_20231128_182357](https://github.com/vasilepi/Space-Rover/assets/149177673/1be776e9-aa58-4f08-a210-6d88f88c86ef)
![IMG_20231128_182509](https://github.com/vasilepi/Space-Rover/assets/149177673/b65162ba-1e0a-43e1-93bd-9398f1511815)
